-- database: d:\DBMS PROJECT\gym\db.sqlite3

-- Use the ▷ button in the top right corner to run the entire file.

-- SELECT * FROM "GYM_EQUIPMENT_CLASSES";

CREATE TABLE MEMBERS (
    MEMBER_ID INTEGER NOT NULL PRIMARY KEY,
    NAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    PASSWORD NOT NULL,
    MEMBER_PLAN NOT NULL,
    FOREIGN KEY (MEMBER_PLAN)
        REFERENCES MEMBERSHIP_PLAN (MEMBERSHIP_PLAN_ID)
    );


CREATE TABLE MEMBER_LOGIN (
    MEMBER_LOGIN_ID INTEGER NOT NULL PRIMARY KEY,
    EMAIL TEXT NOT NULL,
    PASSWORD NOT NULL,
    FOREIGN KEY (EMAIL)
        REFERENCES MEMBERS (EMAIL)
    ,
    FOREIGN KEY (PASSWORD)
        REFERENCES MEMBERS (PASSWORD)
);

CREATE TABLE MEMBERSHIP_PLAN (
    MEMBERSHIP_PLAN_ID INTEGER NOT NULL PRIMARY KEY,
    MEMBERSHIP_NAME TEXT NOT NULL,
    DESCRIPTION TEXT,
    PRICE INTEGER NOT NULL
);


CREATE TABLE PAYMENT (
    PAYMENT_ID NOT NULL PRIMARY KEY,
    AMOUNT INTEGER NOT NULL,
    PAYMENT_DATE DATE NOT NULL,
    MEMBER_ID INTEGER NOT NULL,
    FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBERS (MEMBER_ID)
);

CREATE TABLE TRAINERS (
    TRAINER_ID INTEGER NOT NULL PRIMARY KEY,
    NAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL,
    PHONE INTEGER NOT NULL
);

CREATE TABLE GYM_EQUIPMENT (
    GYM_EQUIPMENT_ID INTEGER NOT NULL PRIMARY KEY,
    EQUIPMENT_NAME TEXT NOT NULL,
    CONDITION TEXT NOT NULL
);

CREATE TABLE ATTENDANCE (
    ATTENDANCE_ID INTEGER NOT NULL PRIMARY KEY,
    ATTENDANCE_DATE DATE NOT NULL,
    MEMBER_ID INTEGER NOT NULL, 
    CLASS_ID INTEGER NOT NULL,
    FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBERS (MEMBER_ID)
    ,
    FOREIGN KEY (CLASS_ID)
        REFERENCES CLASSES (CLASS_ID)
);

CREATE TABLE CLASSES (
    CLASS_ID INTEGER NOT NULL PRIMARY KEY,
    CLASS_NAME TEXT NOT NULL,
    CLASS_DESCRIPTION TEXT,
    CLASS_DATE DATE NOT NULL,
    CLASS_TIME TEXT NOT NULL 
);

CREATE TABLE MEMBER_CLASSES (
    MEMBER_CLASSES_ID INTEGER NOT NULL PRIMARY KEY,
    MEMBER_ID INTEGER NOT NULL,
    CLASS_ID INTEGER NOT NULL,
    FOREIGN KEY (MEMBER_ID)
        REFERENCES MEMBERS (MEMBER_ID)
    ,
    FOREIGN KEY (CLASS_ID)
        REFERENCES CLASSES (CLASS_ID)
);

CREATE TABLE TRAINER_CLASSES (
    TRAINER_CLASSES_ID INTEGER NOT NULL PRIMARY KEY,
    TRAINER_ID INTEGER NOT NULL,
    CLASS_ID INTEGER NOT NULL,
    FOREIGN KEY (TRAINER_ID)
        REFERENCES TRAINERS (TRAINER_ID)
    ,
    FOREIGN KEY (CLASS_ID)
        REFERENCES CLASSES (CLASS_ID)
);

CREATE TABLE GYM_EQUIPMENT_CLASSES (
    GYM_EQUIPMENT_CLASS_ID INTEGER NOT NULL PRIMARY KEY,
    CLASS_ID INTEGER NOT NULL,
    GYM_EQUIPMENT_ID INTEGER NOT NULL,
    FOREIGN KEY (GYM_EQUIPMENT_ID)
        REFERENCES GYM_EQUIPMENT (GYM_EQUIPMENT_ID)
    ,
    FOREIGN KEY (CLASS_ID)
        REFERENCES CLASSES (CLASS_ID)
);

CREATE TABLE GYM_ADMIN (
    GYM_ADMIN_ID INTEGER NOT NULL PRIMARY KEY,
    EMAIL TEXT NOT NULL,
    PASSWORD NOT NULL
);
