# Generated by Django 3.2.19 on 2023-06-30 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230701_0229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='REGISTER',
        ),
    ]
